// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtFPTWXlu-9Pcwanr-fPvm-9HLXk5Q1lo',
    appId: '1:514147421732:web:b0ec872d93c0cd38cf52b1',
    messagingSenderId: '514147421732',
    projectId: 'zylook-e8803',
    authDomain: 'zylook-e8803.firebaseapp.com',
    storageBucket: 'zylook-e8803.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOfUjER2lPvpXzVeSp-Imf-6qpBMGE0o',
    appId: '1:514147421732:android:7fc848b303f3fec6cf52b1',
    messagingSenderId: '514147421732',
    projectId: 'zylook-e8803',
    storageBucket: 'zylook-e8803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjp2-h4OZaRNZlkNmKztOpXOfz9sjy0R0',
    appId: '1:514147421732:ios:5a65abb5c5374b4acf52b1',
    messagingSenderId: '514147421732',
    projectId: 'zylook-e8803',
    storageBucket: 'zylook-e8803.firebasestorage.app',
    iosBundleId: 'com.example.zylook',
  );
}
